name: Pico Compile Check

on:
  push:
  pull_request:

env:
  PICO_SDK_PATH: /opt/pico-sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential git

      - name: Install Pico SDK
        run: |
          sudo git clone https://github.com/raspberrypi/pico-sdk.git $PICO_SDK_PATH
          sudo chown -R $USER:$USER $PICO_SDK_PATH
          cd $PICO_SDK_PATH
          git submodule update --init

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)